### ISSUE TITLE
Feature Considerations

### ISSUE THREAD

**Issue by KAnon20** [ZenonSeth/logistica#22]
1. Allow the wrench to also tell how many nodes are connected to a Logistic Network Controller.

2. Parse search text and remove nasty characters. I accidentally typed a "[" and hit enter, and it crashed Minetest. After launching again, it repeated until I destroyed the Access Point and placed it down again (clearing the search).

3. Maybe add Trash Can support for deleting items after a Mass Storage is full of the item rather than filling Passive Supply Chests (PSC) on the network. The option would be added to the Trash Can, Mass Storage, or behind the scenes in the Trash Can.
I added the Fishing Trap mod and automated it to add to my Network but it filled my 45 PSCs on the network even though I had a Trash can set to delete them after "filling the network". I seriously thought that since the Mass Storage had 8 slots for them and would reach 40960 that they would delete instead of filling my PSCs, and was shocked.

**Comment by ZenonSeth** [comment]
I'll try to fix 2 as soon as possible (today), I thought I had sanitized all input, but I may have changed or missed the AP.

1 sounds like a great idea, though perhaps I can also add it as info to the network controller, or AP, if I add tabs. I'll think about what the best compromise between quick implementation and usability is.

3 also sounds good, but I will have to think about the proper way to do this. It actually may be better to solve it by adding options to each Network Importer as to what types of storage to target, rather than to the trashcan for priority. Will also have a think about this.

**Comment by ZenonSeth** [comment]
Point 2 has been fixed in [Release 1.2.5](https://github.com/ZenonSeth/logistica/releases/tag/1.2.5) - also available on ContentDB.

I will try to work on suggestion 1 and 3 sometime soon, not sure which would be first, but will have more time this weekend.

**Comment by ZenonSeth** [comment]
Suggestions 1 and 3 are now also implemented in [Release 1.2.7](https://github.com/ZenonSeth/logistica/releases/tag/1.2.7) and available on Content DB for download.

Specifically:
- Added [Network Importer](https://github.com/ZenonSeth/logistica/wiki/Logistic-Network:-Moving-Items#network-importer) options to select which types of machines to import items into
- Added [Hyperspanner](https://github.com/ZenonSeth/logistica/wiki/Tools#hyperspanner) advanced usage (sneak+use) to show network machine counts

This should complete this feature request ticket.

**Comment by ZenonSeth** [comment]
I'm going to close this issue as complete, since I believe I've addressed all 3 requests here. Feel free to reopen or post new issue if you think otherwise.
