### ISSUE TITLE
crafting input with replacement duplicated

### ISSUE THREAD

**Issue by programmerjake** [ZenonSeth/logistica#5]
when a recipe has an input that is just given back as a replacement, that input can be duplicated:

Reproduction:
* create world with Minetest Game 5.8.0
* enable Farming Redo (has necessary recipes), Logistica, and Unified Inventory (for convenience)
* create network with 2 Crafting Suppliers, a Supplier Chest, a network controller, and a access point
* program first crafting supplier to make Pineapple Juice with the following recipe:
    | Empty Drinking Glass | Pineapple | Empty Drinking Glass |
    |-|-|-|
    | &nbsp; | Juicer | &nbsp; |
    | &nbsp; | | |
* program second crafting supplier to make Vessels Shelf with the following recipe:
    | Planks | Planks | Planks |
    |-|-|-|
    | Pineapple Juice | Pineapple Juice | Pineapple Juice |
    | Planks | Planks | Planks |
* insert 1 Juicer and a pile of Planks, Empty Drinking Glasses, and Pineapples in the Supplier Chest.
* From Access Point, take Vessel Shelves, observe how you end up with multiple Juicers -- this is a bug.

**Comment by ZenonSeth** [comment]
I've implemented a partial fix that addresses the main problem that caused this duplication, and made a release https://github.com/ZenonSeth/logistica/releases/tag/0.9.5 , also available on [ContentDB](https://content.minetest.net/packages/ZenonSeth/logistica/) - that should prevent the infinite duplication that is happening.

There are however still some issues that are a little harder to resolve due to how the crafting suppliers work - specifically they require the full amount of items to be able to be crafted, which, for recipes such as the one using the juicer, can be done with only 1 juicer. I've left a "bug" of sorts into the code to allow those recipes to still be crafted, but under some circumstances it's still possible to trick it into duplicating that replacement item, it's just much tricker to do now, and should not result in infinite number of them.

**Comment by ZenonSeth** [comment]
This was tricky to fix, but I think I got it - the latest `main` branch should fix this, specifically this commit https://github.com/ZenonSeth/logistica/commit/69d384feadda7f6c9b893b1596217ee8d38b2f82

I am going to test it some more before releasing - if you are still playing and have time, you can test it out too.

**Comment by ZenonSeth** [comment]
Ok, I spent some time testing, and this issue should now be fixed in 0.9.14: https://github.com/ZenonSeth/logistica/releases/tag/0.9.14 -  along with other fixes and improvements. 0.9.14 is also published on ContentDB now.

**Comment by Ocraw** [comment]
Crafting supplier still dupes (or the mass storage itself, not sure who to blame), if a mass storage is in pull mode, the recipe output is taken from the crafting supplier no matter if there are available items in the network. It just pulls the ghost recipe output, leaving it empty, and creating an item for free.

**Comment by ZenonSeth** [comment]
Closing this issue now, as I believed it's fixed. Feel free to reopen if you think it's not.
